// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    var hashchange, nth_child, video;
    $(document).keydown(function(e) {
      switch (e.keyCode) {
        case 37:
          if (!$("*:focus").is("input,textarea") && $("a.previous").length > 0) {
            e.preventDefault();
            return location.href = $("a.previous").attr("href");
          }
          break;
        case 39:
          if (!$("*:focus").is("input,textarea") && $("a.next").length > 0) {
            e.preventDefault();
            return location.href = $("a.next").attr("href");
          }
      }
    });
    $('.inputer').click(function() {
      $(this).hide();
      return $('#search').show().focus();
    });
    $('#search').on('keyup', function(e) {
      var val;
      if (e.keyCode === 13) {
        val = $(this).val().split(' ').join('-');
        return window.location = window.location.origin + '/' + val;
      }
    }).on('blur', function() {
      $(this).hide().val('');
      return $('.inputer').show();
    });
    $('a:has(img)').addClass('image');
    $('a[rel=external]').attr('target', '_blank');
    $('body.thinking .content img').each(function() {
      var img, p;
      img = $(this);
      p = img.parent();
      p.addClass('image');
      if (img.attr('alt') && img.attr('alt') !== '') {
        return p.append("<i>" + (img.attr('alt')) + "</i>");
      }
    });
    $('video').click(function() {
      if (this.paused) {
        return this.play();
      } else {
        return this.pause();
      }
    });
    if (navigator.platform.toLowerCase().indexOf('win') !== -1) {
      $('html').addClass('windows');
    }
    if (!$.support.leadingWhitespace) {
      nth_child = ['zero', 'one', 'two', 'three'];
      $('article:last, div:last, li:last, p:last').addClass('last-child');
      $('.quarter').each(function(i) {
        return $(this).addClass(nth_child[i % 4]);
      });
    }
    hashchange = function() {
      var hash;
      hash = unescape(window.location.hash.slice(1));
      if (hash.match(/(girl|boy)friend/i)) {
        $('link[rel="stylesheet"]').remove();
        $('head').append('<link rel="stylesheet" href="/assets/future-girlfriend/site.css" />');
        $('header').append('<embed src="/assets/future-girlfriend/hello.mp3" width="64" height="34"></embed>');
        $('#team').next().find('img').each(function(i) {
          return $(this).attr('src', $(this).attr('src').replace('/assets/', '/assets/future-girlfriend/'));
        });
      }
      if (hash.match(/(mustache|mustachify)/i)) {
        return $('img').each(function(i) {
          return $(this).attr('src', 'http://mustachify.me/?src=' + encodeURIComponent($(this)[0].src));
        });
      }
    };
    if (window.location.hash) {
      hashchange();
    }
    $(window).bind("hashchange", function() {
      return hashchange();
    });
    $("div.content").fitVids({
      customSelector: ".fitvid"
    });
    if ($("#hero").length > 0) {
      $(window).resize(function() {
        var margin, padding, width;
        if ($(window).width() > 1420) {
          width = (($(window).width() + 50) / 1260) * 100;
          margin = (width - 100) / 2;
          padding = ((1 - (1260 / ($(window).width() + 50))) / 2) * 100;
          return $("body > section h1").width(width.toString() + "%").css("margin-left", "-" + margin.toString() + "%").find("span").css("left", padding.toString() + "%");
        } else {
          return $("body > section h1").width("").css("margin-left", "").find("span").css("left", "");
        }
      }).resize();
      if ($("#hero").find("video").length > 0) {
        video = $("#hero").find("video")[0];
        video.addEventListener("ended", (function(e) {
          video.currentTime = 0.1;
          return video.play();
        }), false);
        if (window.outerWidth >= 700) {
          return video.play();
        }
      }
    }
  });

}).call(this);
